# Generated by Django 5.1.2 on 2024-10-19 10:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=25)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=16)),
                ('steering_wheel', models.CharField(choices=[('левый', 'Левый'), ('правый', 'Правый')], max_length=20)),
                ('box', models.CharField(choices=[('автомат', 'Автомат'), ('механика', 'Механика')], max_length=10)),
                ('condition', models.CharField(choices=[('новый', 'Новый'), ('б/у', 'Б/У')], max_length=10)),
                ('volume', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('date', models.DateField(auto_now_add=True)),
                ('have', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=13)),
                ('last_name', models.CharField(max_length=33)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.marka'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.model'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.user'),
        ),
    ]
